name: CKFloatingText
main: Craftklinik\CKFloatingText
version: 1.2
api: 3.1.1
author: Craftklinik
website: https://craftklinik.de

commands:
  addtag:
    desctiption: Fügt einen Text hinzu!
    permission: afloatingtext.addtag
permissions:
  afloatingtext:
    default: op
    desctiption: 
    children:
      afloatingtext.addtext:
        default: op
        desctiption: 
